name: Check Spark Operator image

on:
  pull_request:
    branches:
      - master

jobs:
  publish-notebook:
    name: Check Spark Operator image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build spark-operator:3.0.0
        run: docker build -t ferlabcrsj/spark-operator:3.0.0 .
        working-directory: spark300_hadoop320
