name: Publish Tagged Image

on:
  push:
    tags:
      - 3.0.0_*
      - 3.1.1_*

jobs:
  publish-notebook:
    name: Publish Spark-Operator notebook image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Spark version  # Without dots (3.0.0 -> 300)
        run: |
          SPARK_VERSION=${GITHUB_REF_NAME%_*}
          echo "SPARK_VERSION=$(echo $SPARK_VERSION | tr -d '.')" >> $GITHUB_ENV
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build spark-operator
        run: docker build -t ferlabcrsj/spark-operator:$GITHUB_REF_NAME .
        working-directory: spark${{ env.SPARK_VERSION }}_hadoop320
      - name: Push spark-operator
        run: docker push ferlabcrsj/spark-operator:$GITHUB_REF_NAME
        working-directory: spark${{ env.SPARK_VERSION }}_hadoop320
